# action.yml
name: 'Buildfish'
description: 'Build SailfishOS apps with Docker'
inputs:
  release:
    description: 'SailfishOS release'
    default: 'latest'
  arch:
    description: 'SailfishOS arch (e.g. armv7hl)'
    default: 'armv7hl'

env:
  SFOS_RELEASE: ${{ inputs.release }}
  SFOS_ARCH: ${{ inputs.arch }}

outputs:
  rpm: # id of output
    description: '???'
runs:
  using: 'docker'
  image: 'Dockerfile'
